* Org Mode
:PROPERTIES:
:TANGLE: ~/.config/nvim/after/plugin/orgmode.lua
:END:

** Setup
   #+BEGIN_SRC lua
   local orgmode = require('orgmode')
   orgmode.setup_ts_grammar()
   orgmode.setup()
   vim.opt.conceallevel = 2
   vim.opt.concealcursor = 'nc'
   #+END_SRC

** Add "Enter" as a multipurpose mapping
   This is a piece of code that will make use of the "Enter" key while on normal
   mode to activate some org actions. This match more closely what happens in emacs
   and can also be easily customized.

   First of all, let's setup a function that will be used to identify org links, since
   I can't use treesitter for that.

   #+BEGIN_SRC lua
   local org_mappings = require('orgmode.org.mappings')

   -- This function will be used instead of treesitter to find links
   local is_link = function ()
     local is_link = org_mappings._get_link_under_cursor()
     if is_link == nil then
       return nil
     end

     return true
   end
   #+END_SRC

   Now, let's create a table that will handle, in order of insertion, all the possible
   actions that should be handled by the "Enter" key in different situations.
   The key of this table should be a Treesitter node type (it's easy to find using the
   treesitter playground plugin) or a function that will return `nil` if it doesn't find 
   what it is supposed to represent, otherwise it doesn't really matter what it returns, but
   it must return something.

   #+BEGIN_SRC lua
   local type_to_action = {
     [is_link] = 'org_mappings.open_at_point',
     timestamp = 'org_mappings.change_date',
     headline = 'org_mappings.todo_next_state',
     listitem = 'org_mappings.toggle_checkbox',
     list = 'org_mappings.toggle_checkbox',
     _default = 'org_mappings.open_at_point'
   }
   #+END_SRC

   Now, these are all the functions that I'll be using to check the type and
   execute the relevant command.

   #+BEGIN_SRC lua
   local function get_action_from_type()
     local ts_utils = require('nvim-treesitter.ts_utils')
     local cur_node = ts_utils.get_node_at_cursor()
     local cur_row = cur_node:range()

     while cur_node ~= nil do
       local nodetype = cur_node:type()

       for identifier, action in pairs(type_to_action) do
         if type(identifier) == 'function' then
           if identifier() ~= nil then
             return action
           end
         elseif nodetype == identifier and identifier ~= '_default' then
           return action
         end
       end

       cur_node = cur_node:parent()
       if cur_node == nil then
         break
       elseif cur_node:range() ~= cur_row then
         break
       end
     end

     return type_to_action._default
   end

   local function toggle_org_item()
     local org = require('orgmode')

     local action = get_action_from_type()

     if action ~= nil then
       org.action(action)
     end
   end
   #+END_SRC

** Create autocommand to add custom keymaps / actions
   In the end, we can create the autocommand that will add this keymap 
   every time a buffer with an Org document is found.

   #+BEGIN_SRC lua :tangle no
   vim.api.nvim_create_autocmd('FileType', {
     pattern = 'org',
     callback = function()
       vim.api.nvim_buf_set_keymap( 0, 'n', '<cr>', '', {
         callback = function ()
           toggle_org_item()
         end,
         noremap = true
       })
     end
   })
   #+END_SRC

** Org Bullets
   #+BEGIN_SRC lua
   require('org-bullets').setup {
     concealcursor = true
   }
   #+END_SRC
